services:
    nginx:
        build:
            context: docker/nginx
        volumes:
            - ./www:/www
        container_name: d_nginx
        restart: always
        ports:
            - 8881:81
        networks:
            - myProject

    php-fpm:
        build:
            context: docker/php-fpm
        restart: always
        container_name: d_php-fpm
        depends_on:
            - mysql
        networks:
            - myProject
        volumes:
            - ./www:/www

    mysql:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        container_name: d_mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_DATABASE=symfony"
            - "MYSQL_USER=admin"
            - "MYSQL_PASSWORD=root"
        ports:
            - 3337:3306
        networks:
            - myProject

networks:
    myProject:
        driver: bridge

# https://hub.docker.com/_/php/tags?name=8.4.3-fpm
# https://hub.docker.com/layers/library/nginx/1.26.2-alpine/images/sha256-c8fac17ccd9d570a6a5d358fca9d295895333ce1498f45c15ba5dfe88da7dfab
# https://hub.docker.com/layers/library/postgres/17.3-alpine/images/sha256-985f604ab90391f765ca6f4f7635c3e98be09178d47f28bf521efcf67da5741c
